services:
  - type: web
    name: habit-tracker
    env: ruby
    region: oregon
    plan: free
    buildCommand: "bundle install && bundle exec rails assets:precompile"
    startCommand: "bundle exec rails server"
    preDeployCommand: "bundle exec rails db:migrate && bundle exec rails db:seed"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: my-postgres-db
    plan: free
