default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
